/**
 * Regenerates src/data/countries.ts from the `world-countries` dataset.
 *
 * The list is generated, not hand-typed, so the codes, regions and flags stay
 * right; run `npx tsx prisma/generate-countries.ts` after bumping the package.
 * Former states (the Soviet Union, the GDR…) are not in ISO 3166-1 and are
 * appended by hand below — caps outlive the countries that pressed them.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import countries from "world-countries";

/** Countries that no longer exist, using their ISO 3166-3 stems as codes. */
const FORMER = [
  { code: "SU", name: "Soviet Union", until: 1991 },
  { code: "DD", name: "German Democratic Republic", until: 1990 },
  { code: "CS", name: "Czechoslovakia", until: 1992 },
  { code: "YU", name: "Yugoslavia", until: 1992 },
];

const rows = countries
  .map((c) => ({
    code: c.cca2,
    name: c.name.common,
    flag: c.flag,
    region: c.region || "Other",
    subregion: c.subregion || c.region || "Other",
    sovereign: c.unMember,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const body = `// Generated by prisma/generate-countries.ts — do not edit by hand.
// Source: the \`world-countries\` package (ISO 3166-1) + the former states below.

export type WorldCountry = {
  /** ISO 3166-1 alpha-2, or a former-state code */
  code: string;
  name: string;
  /** emoji flag; empty for former states, which have none */
  flag: string;
  region: string;
  subregion: string;
  /** true for UN member states, false for territories and dependencies */
  sovereign: boolean;
  /** set on former states: the year they stopped existing */
  until?: number;
};

export const WORLD_COUNTRIES: WorldCountry[] = [
${rows
  .map(
    (r) =>
      `  { code: ${JSON.stringify(r.code)}, name: ${JSON.stringify(r.name)}, flag: ${JSON.stringify(r.flag)}, region: ${JSON.stringify(r.region)}, subregion: ${JSON.stringify(r.subregion)}, sovereign: ${r.sovereign} },`,
  )
  .join("\n")}
];

/** Not in ISO 3166-1 any more, but caps from them are still in the album. */
export const FORMER_COUNTRIES: WorldCountry[] = [
${FORMER.map(
  (f) =>
    `  { code: ${JSON.stringify(f.code)}, name: ${JSON.stringify(f.name)}, flag: "", region: "Former states", subregion: "Former states", sovereign: false, until: ${f.until} },`,
).join("\n")}
];

export const ALL_COUNTRIES: WorldCountry[] = [...WORLD_COUNTRIES, ...FORMER_COUNTRIES];

/** The continents, in the order the countries page shows them. */
export const REGIONS = ["Europe", "Asia", "Africa", "Americas", "Oceania", "Antarctic"] as const;
`;

const out = path.join("src", "data", "countries.ts");
writeFileSync(out, body);
console.log(`Wrote ${rows.length} countries + ${FORMER.length} former states to ${out}`);
